providers:
  anthropic:
    name: Anthropic
    models:
      - name: claude-3-5-sonnet-20240620
        display_name: claude-3-5-sonnet
      - name: claude-3-haiku-20240307
        display_name: claude-3-haiku
  openai:
    name: OpenAI
    models:
      - name: gpt-4o-2024-08-06
        display_name: GPT-4o
      - name: gpt-4o-mini
        display_name: gpt-4o-mini
      - name: o1-preview
        display_name: o1-preview
      - name: o1-mini
        display_name: o1-mini
